default:
	cd server && $(MAKE)
	cd interface && $(MAKE)
	cd ncurses && $(MAKE)
	cd game && $(MAKE)

clean:
	cd server && $(MAKE) clean
	cd interface && $(MAKE) clean
	cd ncurses && $(MAKE) clean
	cd game && $(MAKE) clean
